### ISSUE TITLE
Mysql: undefined method `images' for nil:NilClass

### ISSUE THREAD

**Issue by acrolink** [james1239090/dropzone_carrierwave_multiple_upload#1]
I get `undefined method `images' for nil:NilClass` inside `app/views/products/index.html.erb:16` after switching to Mysql (mysql2) instead of Sqlite.

**Comment by james1239090** [comment]
If you want to use other database
check here first
```remove serialize :images, JSON on model/photo.rb```

https://github.com/carrierwaveuploader/carrierwave#user-content-multiple-file-uploads
